#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Christoph Maier
# SPDX-License-Identifier: Apache-2.0
"""Writes the CACE datasheets and templates of ClassABBiasIn and ClassABBiasOut (GF180MCU, 2026-10-08), proof of
concept subsets of the IHP run_bias.py checks (improvements/bias.md): bias-current accuracy over PVT, DC line
sensitivity, local mismatch. After the first run, edit the generated files, not this script.
Usage: gen_cace.py <ClassABBias macro dir>"""
import os, sys
MAC = os.path.abspath(sys.argv[1])
sys.path.insert(0, os.path.join(MAC, "..", "..", "scripts"))
from xsheet import cace_template, sym_pins

OPTS = (".options savecurrents klu method=gear reltol=1e-4 abstol=1e-15 gmin=1e-15 "
        "SEED=CACE[CACE{seed=12345} + CACE{iterations=0}]\n")
LINES = [("bp", "xbp", 5e-6), ("bn", "xbn", 5e-6), ("bpc", "xbpc", 2e-6), ("bnc", "xbnc", 2e-6), ("abp", "xrp2", 5e-6), ("abn", "xrn2", 5e-6)]
OUT = "echo {vals} > CACE{{simpath}}/CACE{{filename}}_CACE{{N}}.data\n"

def errs():
    s = ""
    for k, dev, nom in LINES:
        s += f"let e_{k} = (abs(@m.x1.{dev}.m0[id])/{nom} - 1)\n"
    return s

def templates(cell, iref_plus, iref_minus, tdir):
    pins = sym_pins(os.path.join(MAC, "schematic", "xschem", cell + ".sym"))
    conns = dict(vdd="vdd", vss="0", vddo="vdd", vsso="0", iref="iref",
                 **{p: p for p in ["vbp", "vbn", "vbpc", "vbnc", "vabp", "vabn"]})
    src = [("Vvdd", "CACE{vdd}", "vdd", "0"), ("Iref", "CACE{i_ref}", iref_plus, iref_minus, "isource")]
    note = (f"{cell} with an ideal reference current CACE{{i_ref}} {'into' if iref_minus == 'iref' else 'out of'} iref; vddo tied to vdd, vsso to vss.\n"
            "Bias currents are the drain currents of the six diodes inside the DUT: XBP, XBN, XBPC, XBNC, XRP2, XRN2\n"
            "(echoed as fractions: CACE shows a unit of % as 100 x the value)\n"
            "(@m.x1.<dev>.m0[id]); errors in % of 5 / 5 / 2 / 2 / 5 / 5 uA.")
    v = " ".join(f"$&e_{k}" for k, _, _ in LINES)
    cace_template(os.path.join(tdir, f"{cell}_tb_dc.sch"), f"Template: bias currents - {cell}", note, f"{cell}.sym", pins, conns, src,
                  OPTS + ".control\nsave all\nop\n" + errs() + "let Idd = -i(Vvdd)\n" + OUT.format(vals=v + " $&Idd") + ".endc\n")
    line = ".control\nsave all\ndc Vvdd 3.0 3.6 0.3\n"
    for k, dev, nom in [LINES[1], LINES[4]]:
        line += f"let i_{k} = abs(@m.x1.{dev}.m0[id])\nlet s_{k} = (i_{k}[2] - i_{k}[0])/i_{k}[1]/0.6\n"
    cace_template(os.path.join(tdir, f"{cell}_tb_line.sch"), f"Template: DC line sensitivity - {cell}",
                  note + "\nvdd = vddo swept 3.0 ... 3.6 V; sensitivity = (I(3.6) - I(3.0)) / I(3.3) / 0.6 V, in %/V.", f"{cell}.sym", pins, conns,
                  src, OPTS + line + OUT.format(vals="$&s_bn $&s_abp") + ".endc\n")

def spec(name, disp, desc, unit, mn, typ, mx):
    f = lambda x: "{value: %s}" % x
    return (f"      {name}:\n        display: {disp}\n        description: '{desc}'\n        unit: '{unit}'\n"
            f"        minimum: {f(mn)}\n        typical: {f(typ)}\n        maximum: {f(mx)}\n")

def yaml(cell, desc, iref_desc):
    errspec = "".join(spec(f"e_{k}", f"Error of {k}", f"Deviation of the v{k} diode current from {nom*1e6:g} uA. Limits are placeholders.",
                           "%", -5, 0, 5) for k, _, nom in LINES)
    mmspec = "".join(spec(f"e_{k}", f"Error of {k} - Mismatch", f"Deviation of the v{k} diode current under local mismatch. Limits are placeholders.",
                          "%", -10, 0, 10) for k, _, nom in LINES)
    v6 = ", ".join(f"e_{k}" for k, _, _ in LINES)
    return f"""# SPDX-FileCopyrightText: 2026 Christoph Maier
# SPDX-License-Identifier: Apache-2.0
#--------------------------------------------------------------
# CACE circuit characterization file, proof of concept (2026-10-08)
# Port of the IHP improvements/sim/run_bias.py checks (accuracy, supply, mc) to gf180mcuD.
# Generated by ../../scripts/gen_cace.py; edit this file from now on.
#--------------------------------------------------------------

name:           {cell}
description:    "{desc}"
PDK:            gf180mcuD

cace_format:    5.2

authorship:
  designer:         Christoph Maier
  creation_date:    October 8, 2026
  license:          Apache-2.0

paths:
  root:             ..
  schematic:        ../schematic/xschem
  netlist:          cace/netlist
  documentation:    cace/_docs
  runs:             cace/_runs

pins:
  vdd:
    description: Analog supply (bias and front end)
    type: power
    direction: inout
    Vmin: 3.0
    Vmax: 3.6
  vss:
    description: Analog ground
    type: ground
    direction: inout
  vddo:
    description: Output-stage supply (rail of OP and its replica RP1)
    type: power
    direction: inout
  vsso:
    description: Output-stage ground (rail of ON and its replica RN1)
    type: ground
    direction: inout
  iref:
    description: {iref_desc}
    type: signal
    direction: inout
  vbp:
    description: PMOS gate line, 5 uA diode BP (unit tails)
    type: signal
    direction: output
  vbn:
    description: NMOS gate line, 5 uA diode BN (fold sinks)
    type: signal
    direction: output
  vbpc:
    description: PMOS cascode gate line, 2 uA diode BPC
    type: signal
    direction: output
  vbnc:
    description: NMOS cascode gate line, 2 uA diode BNC
    type: signal
    direction: output
  vabp:
    description: class-AB P line, 5 uA into RP2 on RP1
    type: signal
    direction: output
  vabn:
    description: class-AB N line, 5 uA into RN2 on RN1
    type: signal
    direction: output

default_conditions:
  vdd:
    description: Analog supply voltage (vddo = vdd)
    display: VDD
    unit: V
    typical: 3.3
  i_ref:
    description: Reference current
    display: Iref
    unit: A
    typical: 5e-6
  corner_mos:
    description: Process corner MOSFET (sm141064.ngspice section)
    display: Corner MOSFET
    typical: typical
  corner_res:
    description: Process corner resistors (sm141064.ngspice section)
    display: Corner resistor
    typical: res_typical
  mm:
    description: Local mismatch switch (sw_stat_mismatch)
    display: Mismatch
    typical: 0
  temp:
    description: Ambient temperature
    display: Temperature
    unit: °C
    typical: 27

parameters:
  dc_params:
    spec:
{errspec}      Idd:
        display: Supply current
        description: Current from vdd (vddo tied to vdd), the reference current not included
        unit: uA
        minimum: {{value: any}}
        typical: {{value: any}}
        maximum: {{value: any}}
    tool:
      ngspice:
        template: {cell}_tb_dc.sch
        format: ascii
        suffix: .data
        variables: [{v6}, Idd]
    plot:
      e_bp_vs_temp:
        type: xyplot
        xaxis: temp
        yaxis: e_bp
        limits: auto
      e_abp_vs_vdd:
        type: xyplot
        xaxis: vdd
        yaxis: e_abp
        limits: auto
      e_bpc_vs_corner_mos:
        type: xyplot
        xaxis: corner_mos
        yaxis: e_bpc
        limits: auto
    conditions:
      i_ref:
        typical: 5e-6
      vdd:
        enumerate: [3.0, 3.3, 3.6]
      corner_mos:
        enumerate: [typical, ss, sf, fs, ff]
      temp:
        enumerate: [-40, 27, 125]

  line_params:
    spec:
{spec("s_bn", "Line sensitivity of vbn", "DC change of the vbn diode current per volt of vdd = vddo, 3.0 ... 3.6 V. Limits are placeholders.", "%/V", -3, 0, 3)}{spec("s_abp", "Line sensitivity of vabp", "DC change of the vabp diode current per volt of vdd = vddo, 3.0 ... 3.6 V. Limits are placeholders.", "%/V", -3, 0, 3)}    tool:
      ngspice:
        template: {cell}_tb_line.sch
        format: ascii
        suffix: .data
        variables: [s_bn, s_abp]
    conditions:
      i_ref:
        typical: 5e-6
      corner_mos:
        enumerate: [typical, ss, sf, fs, ff]
      temp:
        enumerate: [-40, 27, 125]

  mm_params:
    spec:
{mmspec}      Idd:
        display: Supply current - Mismatch
        description: Current from vdd under local mismatch
        unit: uA
        minimum: {{value: any}}
        typical: {{value: any}}
        maximum: {{value: any}}
    tool:
      ngspice:
        template: {cell}_tb_dc.sch
        collate: iterations
        format: ascii
        suffix: .data
        variables: [{v6}, Idd]
    conditions:
      iterations:
        description: Iterations to run
        display: Iterations
        minimum: 1
        maximum: 100
        step: linear
        stepsize: 1
      mm:
        typical: 1
      vdd:
        typical: 3.3
      i_ref:
        typical: 5e-6
      corner_mos:
        typical: typical
      temp:
        typical: 27
"""

if __name__ == "__main__":
    tdir = os.path.join(MAC, "verification", "cace", "templates"); os.makedirs(tdir, exist_ok=True)
    for cell, desc, ird, plus, minus in [
        ("ClassABBiasIn", "Bias of the class-AB driver, variant 1: reference current INTO iref (external PMOS source), GF180MCU 03v3",
         "Reference current input, 5 uA flowing into the pin (NMOS input diode NI)", "0", "iref"),
        ("ClassABBiasOut", "Bias of the class-AB driver, variant 2: reference current OUT of iref (external NMOS sink), GF180MCU 03v3",
         "Reference current output, 5 uA flowing out of the pin (PMOS input diode PI)", "iref", "0")]:
        templates(cell, plus, minus, tdir)
        open(os.path.join(MAC, "verification", "cace", cell + ".yaml"), "w").write(yaml(cell, desc, ird))
        print("wrote", cell)
